name: Flutter Test Coverage

on:
  push:
    branches:
      - main

jobs:
  test-coverage:
    name: Run Tests and Check Coverage
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup FVM
        uses: kuhnroyal/flutter-fvm-config-action/setup@v3

    #   - name: Setup FVM
    #     run: |
    #       curl -fsSL https://raw.githubusercontent.com/leoafarias/fvm/master/install.sh | bash
    #       export PATH="$HOME/.pub-cache/bin:$PATH"
    #       fvm install  # Ensures the correct Flutter version is installed

    #   - name: Use FVM Flutter
    #     run: |
    #       export PATH="$HOME/fvm/default/bin:$PATH"
    #       fvm flutter --version

      - name: Install dependencies
        run: fvm flutter pub get

      - name: Run tests with coverage
        run: fvm flutter test --coverage

      - name: Check coverage threshold
        run: |
          COVERAGE=$(lcov --summary coverage/lcov.info | grep lines | awk '{print $2}' | sed 's/%//')
          THRESHOLD=80  # Set your required coverage percentage
          echo "Coverage: $COVERAGE%"
          if (( $(echo "$COVERAGE < $THRESHOLD" | bc -l) )); then
            echo "Code coverage is below the required threshold of $THRESHOLD%"
            exit 1
          fi
