name: Flutter Test Coverage

on:
  push:
    branches:
      - main

jobs:
  run-checks:
    name: Run Tests and Check Coverage
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup FVM
        uses: kuhnroyal/flutter-fvm-config-action/setup@v3

      - name: Install dependencies
        run: dart pub get

      - name: Run analyzer
        run: dart analyze --fatal-infos --fatal-warnings .

      - name: Run formatter
        run: dart format --set-exit-if-changed .

      - name: Run tests with coverage
        run: flutter test --coverage

      - name: Check coverage threshold
        uses: VeryGoodOpenSource/very_good_coverage@v2
        with:
          path: 'coverage/lcov.info'
          min_coverage: 80
